import {test,expect} from '@playwright/test';
test.describe.serial('FlowDesk 完整链路',()=>{
 test('Dashboard KPI 与最近流程进入编辑器',async({page})=>{await page.goto('/');await expect(page.getByTestId('kpi-grid')).toBeVisible();await expect(page.getByText('流程总数')).toBeVisible();await expect(page.getByText('异常实例',{exact:true}).first()).toBeVisible();await page.getByTestId('recent-workflow').first().click();await expect(page.getByTestId('flow-canvas')).toBeVisible();});
 test('审批配置、保存和双区域校验',async({page})=>{await page.goto('/workflows/wf-1');await page.getByTestId('canvas-node-approval').click();await expect(page.getByTestId('config-panel')).toContainText('审批配置');await page.getByLabel('审批人来源').selectOption({label:'固定角色'});await page.getByTestId('save-node-config').click();await page.getByRole('button',{name:'保存草稿'}).click();await page.getByTestId('validate-button').click();await expect(page.getByTestId('canvas-node-condition')).toHaveClass(/invalid/);await expect(page.getByTestId('issues-panel')).toContainText('条件分支规则未配置');const before=await page.getByTestId('error-count').textContent();expect(Number(before?.match(/\d+/)?.[0])).toBeGreaterThan(0);await page.getByTestId('canvas-node-condition').click();await page.getByLabel('条件字段').selectOption('amount');await page.getByLabel('条件比较值').fill('5000');await page.getByTestId('save-node-config').click();await page.getByTestId('validate-button').click();await expect(page.getByTestId('error-count')).toContainText('0 错误');});
 test('表单预览金额驱动条件分支',async({page})=>{await page.goto('/workflows/wf-1/preview');await expect(page.getByTestId('branch-result')).toContainText('标准分支');await page.getByLabel('申请金额').fill('12000');await expect(page.getByTestId('branch-result')).toContainText('高额分支');});
 test('发布后列表和总览同步',async({page})=>{await page.goto('/workflows/wf-2');await page.getByTestId('publish-button').click();await expect(page.getByRole('status')).toContainText('发布成功');await page.getByRole('link',{name:'流程管理'}).click();const row=page.getByTestId('workflow-row').filter({hasText:'采购合同审批'});await expect(row).toContainText('已发布');await expect(row).toContainText('v3');await page.getByRole('link',{name:'总览'}).click();await expect(page.getByTestId('kpi-grid')).toBeVisible();});
 test('异常实例详情、时间线与当前节点高亮',async({page})=>{await page.goto('/monitor');await page.getByRole('button',{name:'异常',exact:true}).click();await page.getByTestId('instance-row').first().click();await expect(page.getByTestId('instance-detail')).toBeVisible();await expect(page.getByTestId('execution-timeline')).toContainText('提交申请');await expect(page.locator('.runtime-highlight')).toHaveCount(1);});
 test('版本比较并恢复历史版本',async({page})=>{await page.goto('/workflows/wf-2/versions');await expect(page.getByTestId('version-compare')).toContainText('新增节点');await page.getByTestId('restore-version').click();await expect(page).toHaveURL(/\/workflows\/wf-2$/);await expect(page.getByRole('status')).toContainText('已恢复');await expect(page.getByTestId('flow-canvas')).toBeVisible();});
 test('校验未通过时阻止发布',async({page})=>{await page.goto('/workflows/wf-1');await page.getByTestId('publish-button').click();await expect(page.getByRole('status')).toContainText('发现');await expect(page.getByTestId('error-count')).toContainText('1 错误');await expect(page.locator('.draft-indicator')).toContainText('草稿');});
 test('画布撤销与重做',async({page})=>{await page.goto('/workflows/wf-2');const nodes=page.locator('.flow-node');await expect(nodes).toHaveCount(7);await expect(page.getByTestId('undo-button')).toBeDisabled();await page.locator('.palette.approval').click();await expect(nodes).toHaveCount(8);await page.getByTestId('undo-button').click();await expect(nodes).toHaveCount(7);await page.getByTestId('redo-button').click();await expect(nodes).toHaveCount(8);});
 test('节点复制与移除',async({page})=>{await page.goto('/workflows/wf-2');const nodes=page.locator('.flow-node');await page.getByTestId('canvas-node-approval').click();await page.getByTestId('duplicate-node').click();await expect(nodes).toHaveCount(8);await expect(page.locator('.flow-node').filter({hasText:'直属主管审批 副本'})).toHaveCount(1);await page.getByTestId('remove-node').click();await expect(nodes).toHaveCount(7);});
 test('条件节点维护多条带优先级的规则',async({page})=>{await page.goto('/workflows/wf-2');await page.getByTestId('canvas-node-condition').click();await expect(page.getByTestId('rule-card')).toHaveCount(2);await expect(page.getByTestId('rule-card').first()).toContainText('优先级 1');await page.getByTestId('add-rule').click();await expect(page.getByTestId('rule-card')).toHaveCount(3);await expect(page.getByTestId('rule-card').nth(2)).toContainText('优先级 3');await page.getByLabel('删除规则3').click();await expect(page.getByTestId('rule-card')).toHaveCount(2);await page.getByLabel('下移规则1').click();await expect(page.getByTestId('rule-card').first().getByLabel('条件分支名称')).toHaveValue('中额分支：部门负责人复核');});
 test('表单字段设为必填并在预览中校验',async({page})=>{await page.goto('/workflows/wf-2');await page.getByTestId('canvas-node-form').click();await page.getByLabel('必填-附件').check();await page.getByTestId('save-node-config').click();await page.getByRole('button',{name:'预览'}).click();await expect(page).toHaveURL(/\/preview$/);const attachment=page.locator('.form-body label',{hasText:'附件'});await expect(attachment.locator('em')).toBeVisible();await page.getByRole('button',{name:'模拟提交'}).click();await expect(page.locator('.field-error')).toHaveCount(3);});
 test('运行监控按状态和业务域筛选',async({page})=>{await page.goto('/monitor');await page.getByLabel('业务域筛选').selectOption('财务');await expect(page.getByTestId('instance-row')).toHaveCount(16);await expect(page.getByTestId('instance-row').first()).toContainText('财务');await page.getByRole('button',{name:'异常',exact:true}).click();await expect(page.getByTestId('instance-row')).toHaveCount(3);});
 test('刷新后数据仍在',async({page})=>{await page.goto('/workflows/wf-2');const nodes=page.locator('.flow-node');await expect(nodes).toHaveCount(7);await page.locator('.palette.notify').click();await expect(nodes).toHaveCount(8);await page.waitForTimeout(400);await page.reload();await expect(page.locator('.flow-node')).toHaveCount(8);await expect(page.getByTestId('undo-button')).toBeDisabled();});
 test('开始与结束节点缺少连线时阻止发布',async({page})=>{await page.goto('/workflows');await page.getByRole('button',{name:'新建流程'}).click();await expect(page).toHaveURL(/\/workflows\/wf-/);await page.locator('.palette.start').click();await page.locator('.palette.end').click();await page.getByTestId('validate-button').click();await expect(page.getByTestId('issues-panel')).toContainText('开始节点缺少连线');await expect(page.getByTestId('issues-panel')).toContainText('结束节点缺少连线');await expect(page.getByTestId('error-count')).toContainText('2 错误');await page.getByTestId('publish-button').click();await expect(page.getByRole('status')).toContainText('发现 2 个问题');await expect(page.locator('.draft-indicator')).toContainText('草稿');});
 test('版本比较识别连线端点变化',async({page})=>{await page.goto('/workflows/wf-3');const edgePath=page.getByTestId('rf__edge-e3').locator('.react-flow__edge-path');const pt=await edgePath.evaluate((el:SVGPathElement)=>{const p=el.getPointAtLength(el.getTotalLength()/2);const c=el.getScreenCTM()!;return{x:c.e+p.x*c.a,y:c.f+p.y*c.d}});await page.mouse.click(pt.x,pt.y);await page.keyboard.press('Delete');await expect(page.locator('.react-flow__edge')).toHaveCount(6);const src=page.locator('.react-flow__node[data-id="approval"] .react-flow__handle').nth(1);const tgt=page.locator('.react-flow__node[data-id="notify"] .react-flow__handle').nth(0);const sb=(await src.boundingBox())!,tb=(await tgt.boundingBox())!;await page.mouse.move(sb.x+sb.width/2,sb.y+sb.height/2);await page.mouse.down();await page.mouse.move(tb.x+tb.width/2,tb.y+tb.height/2,{steps:12});await page.mouse.up();await expect(page.locator('.react-flow__edge')).toHaveCount(7);await page.getByTestId('publish-button').click();await expect(page.getByRole('status')).toContainText('发布成功');await page.goto('/workflows/wf-3/versions');await page.locator('.compare-select select').first().selectOption({label:'v2 · 2026-07-01 16:20'});await page.locator('.compare-select select').nth(1).selectOption({label:'v4 · 2026-07-11 16:35'});await expect(page.getByTestId('edge-diff-count')).toHaveText('2');await expect(page.getByTestId('edge-diff').filter({hasText:'直属主管审批 → 高额通知'})).toHaveCount(1);await expect(page.getByTestId('edge-diff').filter({hasText:'金额判断 → 高额通知'})).toHaveCount(1);});
 test('校验提示可关闭并自动消失',async({page})=>{await page.goto('/workflows/wf-1');await page.getByTestId('validate-button').click();await expect(page.getByRole('status')).toContainText('发现');await page.getByLabel('关闭提示').click();await expect(page.getByRole('status')).toBeHidden();await page.getByTestId('validate-button').click();await expect(page.getByRole('status')).toBeVisible();await expect(page.getByRole('status')).toBeHidden({timeout:6000});});
});

test('1440px 桌面视觉与控制台验证',async({page})=>{
 const errors:string[]=[]; page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 for(const path of ['/','/workflows/wf-1','/monitor']){await page.goto(path);await page.waitForTimeout(250);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);expect(overflow,`${path} 不应横向溢出`).toBeFalsy()}
 await page.goto('/'); await page.screenshot({path:'test-results/dashboard-1440.png',fullPage:true});
 expect(errors,'浏览器 console 不应出现 error').toEqual([]);
});
